# Generated by Django 4.1.3 on 2022-11-12 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='example_file',
            field=models.FileField(blank=True, null=True, upload_to='posts/examples/'),
        ),
    ]
